#!/bin/bash
#
# ec2-auto-hostname
#
# chkconfig:    2345 50 50
# description:  -
# processname:  -
# config:       -
# pidfile:      -


. /etc/rc.d/init.d/functions
. /etc/profile.d/aws-apitools-common.sh

. /etc/sysconfig/aws.env

. /etc/sysconfig/network

start() {
  HOSTNAME=`ec2-tag-search.sh Name`

  if [ ! -z "$HOSTNAME" ]
  then
    /bin/hostname $HOSTNAME
    /bin/sed -i "s/^\(127.0.0.1.*localhost localhost.localdomain\).*/\1 ${HOSTNAME}/g" /etc/hosts
  fi

  return $?
}

stop() {
  return 0
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit $?