#! /bin/sh
# chkconfig: 35 55 25
# description: ec2-associate-address

### config
EIP=
###

. /etc/init.d/functions
. /etc/profile.d/aws-apitools-common.sh

if [ ! -f /etc/sysconfig/aws.env ]; then
    exit 6;
fi

. /etc/sysconfig/aws.env

start() {
    echo "Start... [instance_id: $INSTANCE_ID, EIP: $EIP"
    ec2-associate-address -i $INSTANCE_ID $EIP --region ap-northeast-1
}

stop() {
    echo "Stop..."
    ec2-disassociate-address $EIP --region ap-northeast-1
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    sleep 3
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage $0 [start|stop|restart]"
esac